<?php

return [
    "encodings" => [
        'USER_WALLET'            => ['label'=>'USER_WALLET','name'=>'Kode Kantong Digital Pengguna'],
        'DEPOSIT'                => ['label'=>'DEPOSIT','name'=>'Kode Deposit'],
        'REFUND'                 => ['label'=>'REFUND','name'=>'Kode Refund'],
        'BILLING'                => ['label'=>'BILLING','name'=>'Kode Billing'],
        'SPLIT_PAYMENT'          => ['label'=>'SPLIT_PAYMENT','name'=>'Kode Split Payment'],
        'TRANSACTION'            => ['label'=>'TRANSACTION','name'=>'Kode Transaksi'],
        'CLINICAL_PATHOLOGY'     => ['label'=>'CLINICAL_PATHOLOGY','name'=>'Kode Master Patologi Klinik'],
        'ANATOMICAL_PATHOLOGY'   => ['label'=>'ANATOMICAL_PATHOLOGY','name'=>'Kode Master Patologi Anatomi'],
        'RADIOLOGY'              => ['label'=>'RADIOLOGY','name'=>'Kode Master Radiology'],
        'TREATMENT'              => ['label'=>'TREATMENT','name'=>'Kode Master Layanan'],
        'MEDICAL_TREATMENT'      => ['label'=>'MEDICAL_TREATMENT','name'=>'Kode Master Tindakan Poliklinik'],
        'PROCUREMENT'            => ['label'=>'PROCUREMENT','name'=>'Kode Pengadaan'],
        'MEDICAL_PROCUREMENT'    => ['label'=>'MEDICAL_PROCUREMENT','name'=>'Kode Pengadaan Item Medis'],
        'OPNAME_STOCK'           => ['label'=>'OPNAME_STOCK','name'=>'Kode Opname Stock'],
        'VISIT_PATIENT'          => ['label'=>'VISIT_PATIENT','name'=>'Kode Kunjungan Pasien'],
        'VISIT_REGISTRATION'     => ['label'=>'VISIT_REGISTRATION','name'=>'Kode Pendaftaran Kunjungan'],
        'VISIT_EXAMINATION'      => ['label'=>'VISIT_EXAMINATION','name'=>'Kode Visitasi'],
        'REFERRAL'               => ['label'=>'REFERRAL','name'=>'Kode Rujukan'],
        'INVOICE'                => ['label'=>'INVOICE','name'=>'Kode Invoice'],
        'INVENTORY'              => ['label'=>'INVENTORY','name'=>'Kode Invoice'],
        'PHARMACY_SALE'          => ['label'=>'PHARMACY_SALE','name'=>'Kode Penjualan Resep Obat/BMHP'],
        'MEDICAL_PROCUREMENT'    => ['label'=>'MEDICAL_PROCUREMENT','name'=>'Kode Pengadaan Obat/BMHP'],
        'MEDICAL_RECORD'         => ['label'=>'MEDICAL_RECORD','name'=>'Rekam Medis'],
        'ORDER_ITEM'             => ['label'=>'ORDER_ITEM','name'=>'Kode Order Item'],
        'DISTRIBUTION_ITEM'      => ['label'=>'DISTRIBUTION_ITEM','name'=>'Kode Distribusi Item'],
        'ITEM_CODE'              => ['label'=>'ITEM_CODE','name'=>'Kode Item'],
        'MEDICAL_ITEM_CODE'      => ['label'=>'MEDICAL_ITEM_CODE','name'=>'Kode Item Medis'],
        'MEDICINE_CODE'          => ['label'=>'MEDICINE_CODE','name'=>'Kode Obat'],
        'MEDICTOOL_CODE'         => ['label'=>'MEDICTOOL_CODE','name'=>'Kode BMHP'],
        'MCU_PACKAGE_CODE'       => ['label'=>'MCU_PACKAGE_CODE','name'=>'Kode Paket MCU'],
        'REFERENCE_ID_LAB'       => ['label'=>'REFERENCE_ID_LAB','name'=>'Kode Referensi Laboratorium'],
    ],
];