<?php

return [
    "encodings" => [
        'USER_WALLET'            => ['flag'=>'USER_WALLET','name'=>'Kode Kantong Digital Pengguna'],
        'DEPOSIT'                => ['flag'=>'DEPOSIT','name'=>'Kode Deposit'],
        'REFUND'                 => ['flag'=>'REFUND','name'=>'Kode Refund'],
        'BILLING'                => ['flag'=>'BILLING','name'=>'Kode Billing'],
        'SPLIT_PAYMENT'          => ['flag'=>'SPLIT_PAYMENT','name'=>'Kode Split Payment'],
        'TRANSACTION'            => ['flag'=>'TRANSACTION','name'=>'Kode Transaksi'],
        'CLINICAL_PATHOLOGY'     => ['flag'=>'CLINICAL_PATHOLOGY','name'=>'Kode Master Patologi Klinik'],
        'ANATOMICAL_PATHOLOGY'   => ['flag'=>'ANATOMICAL_PATHOLOGY','name'=>'Kode Master Patologi Anatomi'],
        'RADIOLOGY'              => ['flag'=>'RADIOLOGY','name'=>'Kode Master Radiology'],
        'TREATMENT'              => ['flag'=>'TREATMENT','name'=>'Kode Master Layanan'],
        'MEDICAL_TREATMENT'      => ['flag'=>'MEDICAL_TREATMENT','name'=>'Kode Master Tindakan Poliklinik'],
        'PROCUREMENT'            => ['flag'=>'PROCUREMENT','name'=>'Kode Pengadaan'],
        'MEDICAL_PROCUREMENT'    => ['flag'=>'MEDICAL_PROCUREMENT','name'=>'Kode Pengadaan Item Medis'],
        'OPNAME_STOCK'           => ['flag'=>'OPNAME_STOCK','name'=>'Kode Opname Stock'],
        'VISIT_PATIENT'          => ['flag'=>'VISIT_PATIENT','name'=>'Kode Kunjungan Pasien'],
        'VISIT_REGISTRATION'     => ['flag'=>'VISIT_REGISTRATION','name'=>'Kode Pendaftaran Kunjungan'],
        'VISIT_EXAMINATION'      => ['flag'=>'VISIT_EXAMINATION','name'=>'Kode Visitasi'],
        'REFERRAL'               => ['flag'=>'REFERRAL','name'=>'Kode Rujukan'],
        'INVOICE'                => ['flag'=>'INVOICE','name'=>'Kode Invoice'],
        'INVENTORY'              => ['flag'=>'INVENTORY','name'=>'Kode Invoice'],
        'PHARMACY_SALE'          => ['flag'=>'PHARMACY_SALE','name'=>'Kode Penjualan Resep Obat/BMHP'],
        'MEDICAL_PROCUREMENT'    => ['flag'=>'MEDICAL_PROCUREMENT','name'=>'Kode Pengadaan Obat/BMHP'],
        'MEDICAL_RECORD'         => ['flag'=>'MEDICAL_RECORD','name'=>'Rekam Medis'],
        'ORDER_ITEM'             => ['flag'=>'ORDER_ITEM','name'=>'Kode Order Item'],
        'DISTRIBUTION_ITEM'      => ['flag'=>'DISTRIBUTION_ITEM','name'=>'Kode Distribusi Item'],
        'ITEM_CODE'              => ['flag'=>'ITEM_CODE','name'=>'Kode Item'],
        'MEDICAL_ITEM_CODE'      => ['flag'=>'MEDICAL_ITEM_CODE','name'=>'Kode Item Medis'],
        'MEDICINE_CODE'          => ['flag'=>'MEDICINE_CODE','name'=>'Kode Obat'],
        'MEDICTOOL_CODE'         => ['flag'=>'MEDICTOOL_CODE','name'=>'Kode BMHP'],
        'MCU_PACKAGE_CODE'       => ['flag'=>'MCU_PACKAGE_CODE','name'=>'Kode Paket MCU'],
        'REFERENCE_ID_LAB'       => ['flag'=>'REFERENCE_ID_LAB','name'=>'Kode Referensi Laboratorium'],
    ],
];